name: 贪吃蛇提交记录生成器

on:
  schedule:
    - cron: "0 0 * * *"  # 每天凌晨执行
  workflow_dispatch:     # 支持手动运行

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 生成贪吃蛇 SVG
        uses: Platane/snk@v3
        with:
          github_user_name: musklh
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: 上传 SVG 到 output 分支
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
